# Generated by Django 5.0 on 2024-09-29 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0002_vote_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='likes',
            field=models.ManyToManyField(blank=True, default=0, related_name='liked_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
