# Generated by Django 5.0 on 2024-10-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0003_vote_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
